import json

import requests
import streamlit as st

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
DEFAULT_MODEL = "openrouter/free"

SYSTEM_PROMPT = """Anda adalah FinAI, asisten Financial Intelligence untuk analisis data keuangan bank.

ATURAN WAJIB:
1. Jawab hanya berdasarkan EVIDENCE yang diberikan oleh Python. EVIDENCE adalah satu-satunya sumber fakta dan angka.
2. Jangan mengarang angka, periode, tren, penyebab, target, atau informasi lain yang tidak ada di EVIDENCE.
3. Jangan menebak maksud pengguna. Jika pertanyaan belum jelas, Python seharusnya sudah menghentikan permintaan sebelum sampai ke Anda. Jika masih ada ambiguitas, minta klarifikasi secara singkat.
4. Jangan mengubah periode yang ada di EVIDENCE dan jangan menggunakan periode dari percakapan sebelumnya sebagai fakta.
5. Pesan assistant sebelumnya hanya konteks percakapan, BUKAN sumber data. Jangan mengambil angka dari pesan tersebut.
6. Jika EVIDENCE tidak memuat data yang diperlukan, katakan bahwa data tersebut tidak tersedia. Jangan melakukan estimasi atau inferensi yang tidak didukung EVIDENCE.
7. Untuk pertanyaan sebab-akibat, jelaskan hanya faktor yang dapat didukung langsung oleh angka/kelompok data dalam EVIDENCE. Gunakan frasa seperti “berdasarkan data” bila menyimpulkan dari perubahan angka.
8. Jangan menampilkan proses berpikir internal, self-talk, langkah pencarian, atau kalimat seperti “mari kita cek”, “mungkin pengguna bermaksud”, “let's check”, atau dugaan typo.
9. Jangan memberikan informasi yang tidak diperlukan untuk menjawab pertanyaan.
10. Gunakan bahasa Indonesia yang ringkas, jelas, dan profesional.
11. Jika pertanyaan meminta satu angka, berikan angka tersebut terlebih dahulu. Tambahkan konteks hanya jika diperlukan.
12. Unit angka mengikuti EVIDENCE. Jangan mengubah satuan tanpa menyebutkannya.
13. OUTPUT HARUS HANYA JAWABAN FINAL untuk pengguna. Jangan pernah menampilkan reasoning, chain-of-thought, langkah analisis, pemeriksaan evidence, self-talk, draft, atau label seperti “Analysis”, “Thinking process”, “Let's check”, “Response”.
14. Jangan menulis ulang EVIDENCE atau isi prompt.

Format jawaban:
- Pertanyaan fakta sederhana: satu jawaban langsung.
- Perbandingan: nilai periode yang dibandingkan + perubahan jika dapat dihitung dari EVIDENCE.
- Analisis: kesimpulan singkat lalu faktor pendukung yang benar-benar ada di EVIDENCE.
"""


def get_api_key():
    try:
        key = st.secrets.get("OPENROUTER_API_KEY", "")
        if not key:
            key = st.secrets.get("api_key", "")
        return str(key).strip() if key else None
    except Exception:
        return None


def _clean_final_answer(content):
    """Fail closed when a model leaks reasoning into the visible content."""
    text = str(content or "").strip()
    if not text:
        return ""

    lowered = text.lower()
    reasoning_markers = [
        "here's a thinking process:", "here is a thinking process:",
        "thinking process:", "chain of thought:", "reasoning:",
        "let's analyze", "let's check", "mari kita cek", "langkah analisis:",
    ]
    if any(marker in lowered for marker in reasoning_markers):
        # Prefer an explicit final-answer section if the model supplied one.
        for final_marker in ["response:", "jawaban:", "final answer:", "jawaban akhir:"]:
            idx = lowered.rfind(final_marker)
            if idx >= 0:
                candidate = text[idx + len(final_marker):].strip(" :\n")
                if candidate:
                    return candidate
        # No trustworthy final section: do not expose the leaked reasoning.
        return ""

    return text


def chat(messages, model=DEFAULT_MODEL, timeout=45, evidence=None, financial_context=None):
    """Call OpenRouter with Python-generated evidence as the only data source.

    ``financial_context`` remains accepted for compatibility with older callers,
    but new code should pass ``evidence``.
    """
    api_key = get_api_key()
    if not api_key:
        return {"ok": False, "error": "API key OpenRouter belum ditemukan di Streamlit Secrets."}

    if evidence is None:
        evidence = financial_context
    if evidence is None:
        return {"ok": False, "error": "Evidence keuangan belum tersedia."}

    # Never send the full dataframe or application state. Only the deterministic
    # evidence object generated by Python is serialized into the system prompt.
    evidence_json = json.dumps(evidence, ensure_ascii=False, allow_nan=False, separators=(",", ":"))
    system_content = SYSTEM_PROMPT + "\n\nEVIDENCE DARI PYTHON (SUMBER FAKTA SATU-SATUNYA):\n" + evidence_json

    # Keep a small conversation window for follow-up questions. Previous
    # assistant messages are explicitly treated as non-authoritative by prompt.
    payload_messages = [{"role": "system", "content": system_content}]
    payload_messages.extend(messages[-8:])

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://demuy89.streamlit.app",
        "X-Title": "FinAI - Financial Intelligence",
    }

    payload = {
        "model": model,
        "messages": payload_messages,
        "temperature": 0.0,
        "max_tokens": 350,
        "reasoning": {"exclude": True},
    }

    try:
        response = requests.post(
            OPENROUTER_URL,
            headers=headers,
            json=payload,
            timeout=timeout,
        )
    except requests.RequestException as exc:
        return {"ok": False, "error": f"Koneksi ke OpenRouter gagal: {exc}"}

    if response.status_code != 200:
        try:
            error_data = response.json().get("error", {})
            message = error_data.get("message") or response.text
        except Exception:
            message = response.text
        return {"ok": False, "error": f"OpenRouter HTTP {response.status_code}: {message}"}

    try:
        data = response.json()
        choices = data.get("choices") or []
        if not choices:
            return {"ok": False, "error": "OpenRouter mengembalikan response tanpa choices."}

        message = choices[0].get("message") or {}
        content = message.get("content")
        if isinstance(content, list):
            content = "".join(
                str(part.get("text", "")) if isinstance(part, dict) else str(part)
                for part in content
            )

        # Do not expose hidden/reasoning fields to the user. If content is
        # absent, fail closed instead of returning chain-of-thought/reasoning.
        cleaned = _clean_final_answer(content)
        if not cleaned:
            return {"ok": False, "error": "Model tidak mengembalikan jawaban final yang dapat ditampilkan."}

        return {"ok": True, "content": cleaned}
    except Exception as exc:
        return {"ok": False, "error": f"Gagal membaca response OpenRouter: {exc}"}
